{
    "th07 Menu Start": "ゲームを開始します",
    "th07 Menu Extra Start": "エキストラステージを開始します",
    "th07 Menu Practice Start": "ステージを選択し、練習を開始します",
    "th07 Menu Result": "過去のスコアやスペルカードの取得歴を見られます",
    "th07 Menu Music Room": "音楽を聴けます",
    "th07 Menu Replay": "リプレイを鑑賞できます",
    "th07 Menu Option": "各種設定できます",
    "th07 Menu Quit": "いろいろと終了します",
    "th07 Option Player": "プレイヤーの初期数を変更します。（初期設定　３）",
    "th07 Option Graphic": "画面の色数を変更します。３２ＢＩＴだと最も綺麗に表示されます。",
    "th07 Option BGM": "ＢＧＭの再生方法を変更します。（初期設定　ＷＡＶ）",
    "th07 Option Sound": "効果音を再生するか選択します",
    "th07 Option Window Mode": "ウィンドウかフルスクリーンか選択します",
    "th07 Option Slow Mode": "弾が多い場面でわざと処理落ちさせます(スコア、リプレイ記録不可)",
    "th07 Option Reset": "全て初期設定にします",
    "th07 Option Key Config": "パッド操作のボタン配置を変更します",
    "th07 Option Quit": "おいそれと終了します",
    "th07 Key Shot": "ショット、決定ボタンを設定します",
    "th07 Key Bomb": "ボム、キャンセルボタンを設定します",
    "th07 Key Slow": "低速移動ボタンを設定します",
    "th07 Key Skip": "メッセージスキップボタンを設定します",
    "th07 Key Pause": "ポーズボタンを設定します",
    "th07 Key Up": "上移動ボタンを設定します",
    "th07 Key Down": "下移動ボタンを設定します",
    "th07 Key Left": "左移動ボタンを設定します",
    "th07 Key Right": "右移動ボタンを設定します",
    "th07 Key ShotSlow": "ショット押しっぱなしで低速移動になるようにします",
    "th07 Key Reset": "初期設定に戻します",
    "th07 Key Quit": "おおよそ終了します",
    "th08 Menu Spell Practice": "敵にスペルカード戦をお願いします",
    "th08 Option BGM Volume": "ＢＧＭの音量を調整します",
    "th08 Option SE Volume": "効果音の音量を調整します",
    "th08 Spell Practice Description": "ステージ    取得/挑戦可能/総数（()内は全キャラ合計）",
    "th08 Spell Practice Percentages": "取得率　（キャラ別／総合）",
    "th09 Menu Story Start": "花映塚モードを開始します",
    "th09 Menu Extra Start": "エキストラモードを開始します",
    "th09 Menu Match Start": "対人戦、対CPU戦、ウォッチモードを開始します",
    "th09 Menu Replay": "リプレイを再生します",
    "th09 Menu Result": "記録を見ます",
    "th09 Menu Music Room": "音楽室に入ります",
    "th09 Option BGM": "ＢＧＭの再生方法を変更します。＊現在まだMIDIは未対応です",
    "th09 Option Key Config": "操作系の設定をします",
    "th09 Key Side": "１Ｐ、２Ｐを選択します",
    "th09 Key Control Type": "PAD1,2:パッド使用、Full,Left,Right:キーボード使用",
    "th09 Key Charge Type": "チャージボタンの動作、Slow:低速移動、Charge:チャージ",
    "th09 Key Shot": "ショットボタンを設定します",
    "th09 Key Bomb": "ボムボタンを設定します",
    "th09 Key Slow": "低速、及びチャージボタンを設定します",
    "th06 Bomb Reimu A": "霊符「夢想封印」",
    "th06 Bomb Reimu B": "夢符「封魔陣」",
    "th06 Bomb Marisa A": "魔符「スターダストレヴァリエ」",
    "th06 Bomb Marisa B": "恋符「マスタースパーク」",
    "th07 Bomb Reimu A unfocused": "霊符「夢想封印　散」",
    "th07 Bomb Reimu A focused": "霊符「夢想封印　集」",
    "th07 Bomb Reimu B focused": "夢符「二重結界」",
    "th07 Bomb Marisa A focused": "魔符「ミルキーウェイ」",
    "th07 Bomb Marisa B unfocused": "恋符「ノンディレクショナルレーザー」",
    "th07 Bomb Sakuya A unfocused": "幻符「インディスクリミネイト」",
    "th07 Bomb Sakuya A focused": "幻符「殺人ドール」",
    "th07 Bomb Sakuya B unfocused": "時符「パーフェクトスクウェア」",
    "th07 Bomb Sakuya B focused": "時符「プライベートスクウェア」",
    "th08 Bomb Reimu": "霊符「夢想妙珠」",
    "th08 Bomb Reimu Last": "神霊「夢想封印　瞬」",
    "th08 Bomb Yukari": "境符「四重結界」",
    "th08 Bomb Yukari Last": "境界「永夜四重結界」",
    "th08 Bomb Marisa Last": "魔砲「ファイナルスパーク」",
    "th08 Bomb Alice": "魔符「アーティフルサクリファイス」",
    "th08 Bomb Alice Last": "魔操「リターンイナニメトネス」",
    "th08 Bomb Sakuya Last": "幻葬「夜霧の幻影殺人鬼」",
    "th08 Bomb Remilia": "紅符「不夜城レッド」",
    "th08 Bomb Remilia Last": "紅魔「スカーレットデビル」",
    "th08 Bomb Youmu": "人符「現世斬」",
    "th08 Bomb Youmu Last": "人鬼「未来永劫斬」",
    "th08 Bomb Yuyuko": "死符「ギャストリドリーム」",
    "th08 Bomb Yuyuko Last": "死蝶「華胥の永眠」",
    "th08 Spell Dissolve": "「ディゾルブスペル」",
    "th08 Spell Resurrection": "「リザレクション」",
    "th08 Music Room spoiler 1": "＊＊＊注意＊＊＊",
    "th08 Music Room spoiler 2": "　この曲はまだ、ゲーム中で流れておりません",
    "th08 Music Room spoiler 3": "　自分でプレイする前に聴きたくない、コメントを見たくない、",
    "th08 Music Room spoiler 4": "　という方は一刻も早くここから立ち去る事をお奨めします。",
    "th08 Music Room spoiler 5": "　",
    "th08 Music Room spoiler 6": "　（なお、ここで決定ボタンを押せば、他の曲と同様、",
    "th08 Music Room spoiler 7": "　　曲の再生とコメント表示が行われますので、注意）",
    "th09 Music Room spoiler 1": "***** 注意 *****",
    "th09 Music Room spoiler 2": "  \nこの曲はまだゲーム中で再生されたことがありません。",
    "th09 Music Room spoiler 3": "  \n一応聴くことは出来ますが、曲名とコメントは見ることが出来ません。",
    "th10 Music Room spoiler 1": "　　＊＊選択した曲はまだゲーム中で再生されていません＊＊",
    "th10 Music Room spoiler 2": "　　　　曲のコメントがネタバレになる恐れがあります。",
    "th10 Music Room spoiler 3": "　　　　　　　　　それでも再生しますか？",
    "th10 Music Room spoiler 4": "　　　再生したい方は、もう一度決定ボタンを押してください。",
    "th10 Music Room spoiler 5": "　　　再生したくない方は、カーソルを移動してください。",
    "th13 spell nothing": " Nothing ... ",
    "th143 Trophy Format": "『%s』",
    "th143 Trophy Get": "の異名を手に入れた",
    "th10 Dialog Prompt": "ウィンドウモードを選択してください",
    "th10 Dialog Fullscreen": "フルスクリーン",
    "th10 Dialog Always ask": "起動時に毎回聞く",
    "th11 Dialog Fullscreen 640": "フルスクリーン(640×480)",
    "th11 Dialog Window 640": "ウィンドウ(640×480)",
    "th11 Dialog Window 960": "ウィンドウ(960×720)",
    "th11 Dialog Window 1280": "ウィンドウ(1280×960)",
    "th11 Dialog Game Start": "ゲーム起動",
    "th14 Dialog Prompt": "解像度を選択してください",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280×960 （推奨）",
    "th14 Dialog Fullscreen": "フルスクリーンで起動する",
    "th14 Dialog Always ask": "起動時に毎回訊ねる",
    "th10 JP": "東方風神録",
    "alcostg JP": "黄昏酒場",
    "th11 JP": "東方地霊殿",
    "th12 JP": "東方星蓮船",
    "th125 JP": "ダブルスポイラー",
    "th128 JP": "妖精大戦争",
    "th13 JP": "東方神霊廟",
    "th14 JP": "東方輝針城",
    "th143 JP": "弾幕アマノジャク",
    "th15 JP": "東方紺珠伝",
    "th06 config": "東方紅魔郷　環境カスタムプログラム",
    "th07 config": "東方妖々夢　環境カスタムプログラム",
    "th08 config": "東方永夜抄　環境カスタムプログラム",
    "th09 config": "東方花映塚　環境カスタムプログラム",
    "th095 config": "東方文花帖　環境カスタムプログラム",
    "th10 config": "東方風神録　環境カスタムプログラム",
    "alcostg config": "黄昏酒場　環境カスタムプログラム",
    "th11 config": "東方地霊殿　環境カスタムプログラム",
    "th12 config": "東方星蓮船　環境カスタムプログラム",
    "th125 config": "ダブルスポイラー　～ 東方文花帖 　環境カスタムプログラム",
    "th128 config": "妖精大戦争　～ 東方三月精 　環境カスタムプログラム",
    "th13 config": "東方神霊廟　環境カスタムプログラム",
    "th14 config": "東方輝針城　環境カスタムプログラム",
    "th143 config": "弾幕アマノジャク　環境カスタムプログラム",
    "th15 config": "東方紺珠伝　環境カスタムプログラム",
    "th06 up": "上 ",
    "th06 down": "下 ",
    "th06 left": "左 ",
    "th06 right": "右 ",
    "DirectInput fix": "DirectInputを使用",
    "DirectInput fix, layout-dependent shot key": "DirectInputを使用（ショットキー: %c）",
    "th06 vertex": "頂点バッファを使用しない",
    "th06 fog": "フォグを使用しない",
    "th06 16bit textures": "16Bitsのテクスチャしか使用しない",
    "th06 Gouraud shading": "グーローシェーディングを使用を抑制",
    "th06 color composition": "テクスチャに一切のカラー合成をしない",
    "th06 rasterizer mode": "リファレンスラスタライザモードで起動",
    "th06 clear buffer": "毎回、バックバッファをクリア",
    "th06 minimum graphics": "必要最低限のものを残して表示しない",
    "th06 depth test": "デプステストをOFFにする",
    "th06 force frame": "強制的に６０フレームにする",
    "th06 fullscreen": "フルスクリーン",
    "th06 windowed": "ウィンドウ",
    "th06 full rate": "毎回（通常）",
    "th06 half rate": "１／２回",
    "th06 third rate": "１／３回",
    "th06 32bits mode": "３２Bits",
    "th06 16bits mode": "１６Bits",
    "th06 accept": "決定",
    "th06 cancel": "キャンセル",
    "th06 screen mode": "ウィンドウスタイル",
    "th06 refresh rate": "描画間隔",
    "th06 colors": "画面モード",
    "th06 pad X axis": "パッドの遊び左右(1～1000)",
    "th06 pad Y axis": "パッドの遊び上下(1～1000)",
    "th06 check pad": "パッド十字キーの確認",
    "th06 config saved caption": "確認",
    "th06 config saved text": "環境を書き換えました",
    "th07 16bits textures": "16Bitsのテクスチャ使用を強制",
    "th07 BGM memory": "BGMをメモリに読み込む",
    "th07 draw screen": "画面周りを毎回描画",
    "th07 VSync": "垂直同期を取らない",
    "th07 fullscreen": "フルスクリーン(推奨)",
    "th07 low effects": "最低",
    "th07 medium effects": "控えめ",
    "th07 high effects": "美麗(推奨)",
    "th07 32bits mode": "３２Bits(推奨)",
    "th07 effect quality": "エフェクトの質",
    "th08 fog": "フォグを使用しない（非推奨）",
    "th08 color composition": "テクスチャにカラー合成をしない（禁止）",
    "th08 depth test": "デプステストをOFFにする（非推奨）",
    "th08 rasterizer mode": "リファレンスラスタライザモードで起動（禁止）",
    "th08 VSync": "垂直同期を取らない（非推奨）",
    "th09 full rate": "毎回（推奨）",
    "th09 1P controller": "1P側の操作方法",
    "th09 2P controller": "2P側の操作方法",
    "th09 gamepad 1": "ゲームパッド１",
    "th09 gamepad 2": "ゲームパッド２",
    "th09 all keyboard": "キーボード全部",
    "th09 left side keyboard": "左側",
    "th09 right side keyboard": "右側",
    "th09 no save": "保存せずに終了",
    "th09 save": "保存して終了",
    "th10 faith meter": "信仰減少カウンタをプレイヤーの近くに表示する",
    "th10 screen mode": "ウィンドウモード",
    "th10 always ask": "毎回訊ねる",
    "th10 slowshot": "ショットボタン押しっぱなしで低速移動する",
    "th11 input latency": "入力のレイテンシ",
    "th11 stable input": "安定（通常では上手く動かない場合）",
    "th11 normal input": "通常（CPUの占拠率が低い）",
    "th11 automatic input": "自動（最速の反応を自動的に検出）＊推奨",
    "th11 fast input": "高速（自動では正常に動作しない場合）",
    "th11 input description": "　入力のレイテンシでは入力のレスポンスを微調整する事が出来ます。\n　「安定」「通常」は前作までのレスポンスです。\n　「自動」はマシンの性能が十分なのであれば最速のレスポンスを期待できます。\n　「高速」は「自動」と同程度のレスポンスですが、一部画面が乱れる事があります。\n　＊描画間隔が「毎回」以外では無効です＊",
    "th11 always ask": "起動時に毎回訊ねる",
    "th11 sensitivity description": "上下左右の入力が鈍い場合は減らし、敏感過ぎる場合は増やしてください\n（default:600）",
    "th11 joypad sensitivity": "パッドの遊び",
    "th11 default": "初期設定に戻す",
    "th13_ascii_spell_score": "SCORE %8d0  %4d/%4d",
    "th13_ascii_spell_unknown": "SCORE        00  ----/----",
    "th13_ascii_spell_game": "GAME MODE        %4d/%4d",
    "th14_ascii_bonus": "BONUS %.1f",
    "th14_ascii_no_bonus": "NO BONUS",
    "th10_ascii_stage_1": "Stage 1 ",
    "th10_ascii_stage_2": "Stage 2 ",
    "th10_ascii_stage_3": "Stage 3",
    "th10_ascii_stage_4": "Stage 4",
    "th10_ascii_stage_5": "Stage 5",
    "th10_ascii_stage_6": "Stage 6",
    "th10_ascii_stage_clear": "Clear  ",
    "th10_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:--  Stage -  ---%",
    "th10_ascii_ranking": "            Score Ranking!!",
    "th13_ascii_credit": "Credit %d",
    "th07 Spell Result Character Select": "%s  %3d枚中%3d枚取得（キャラ切り替え↓↑）",
    "th07 Stats ReimuA": "博麗 霊夢 (霊)",
    "th07 Stats ReimuB": "博麗 霊夢 (夢)",
    "th07 Stats MarisaA": "霧雨 魔理沙 (魔)",
    "th07 Stats MarisaB": "霧雨 魔理沙 (恋)",
    "th07 Stats SakuyaA": "十六夜 咲夜 (幻)",
    "th07 Stats SakuyaB": "十六夜 咲夜 (時)",
    "th07 Stats Total (All Characters)": "全主人公合計",
    "th07 Stats Time Since Startup": "総起動時間 %.2d:%.2d:%.2d",
    "th07 Stats Total Playtime": "総プレイ時間 %.2d:%.2d:%.2d",
    "th07 Stats Play Count +Phantasm": "プレイ回数",
    "th07 Stats Play Count": "プレイ回数",
    "th07 Stats Character Format +Phantasm": "%s %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Character Format": "%s %6d %6d %6d %6d %6d %6d",
    "th07 Stats Clear Count +Phantasm": "クリア回数 %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Clear Count": "クリア回数 %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue +Phantasm": "コンティニュー %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue": "コンティニュー %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice +Phantasm": "プラクティス %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice": "プラクティス %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries +Phantasm": "リトライ回数 %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries": "リトライ回数 %6d %6d %6d %6d %6d %6d",
    "th08 Spell Result Character Select": "%3d/%3d（キャラ切り替え↓↑）",
    "th08 Stats Time Since Startup": "総起動時間 %.2d:%.2d:%.2d",
    "th08 Stats Total Playtime": "総プレイ時間 %.2d:%.2d:%.2d",
    "th08 Stats Play Count": "プレイ回数",
    "th08 Stats Reimu & Yukari": "霊夢＆紫",
    "th08 Stats Marisa & Alice": "魔理沙＆アリス",
    "th08 Stats Sakuya & Remilia": "咲夜＆レミリア",
    "th08 Stats Youmu & Yuyuko": "妖夢＆幽々子",
    "th08 Stats Reimu": "博麗　霊夢",
    "th08 Stats Yukari": "八雲　紫",
    "th08 Stats Marisa": "霧雨　魔理沙",
    "th08 Stats Alice": "アリス・Ｍ",
    "th08 Stats Sakuya": "十六夜　咲夜",
    "th08 Stats Remilia": "レミリア・Ｓ",
    "th08 Stats Youmu": "魂魄　妖夢",
    "th08 Stats Yuyuko": "西行寺　幽々子",
    "th08 Stats Total (All Characters)": "全主人公合計",
    "th08 Stats Clear Count": "クリア回数 %6d %6d %6d %6d %6d %6d",
    "th08 Stats Continue": "コンティニュー %6d %6d %6d %6d %6d %6d",
    "th08 Stats Practice": "プラクティス %6d %6d %6d %6d %6d %6d",
    "th08 Stats Character Format": "%s %6d %6d %6d %6d %6d %6d",
    "th08 Spell Practice Easy Mode": "初月（イージー）",
    "th08 Spell Practice Normal Mode": "三日月（ノーマル）",
    "th08 Spell Practice Hard Mode": "上つ弓張（ハード）",
    "th08 Spell Practice Lunatic Mode": "待宵（ルナティック）",
    "th08 Spell Practice Extra Mode": "望月（エキストラ）",
    "th08 Spell Practice Last Word": "極意（ラストワード）",
    "th08 Spell Practice List Description": "取得数/挑戦数（()内は本編での集計）",
    "th08 Spell Practice Owner/Difficulty Line": "使用者  %s　　%s %s",
    "th08 Spell Practice Highscore Title": "取得数/挑戦数[最高点]　%s　全主人公合計",
    "th08 Spell Practice Comment": "カードの補足",
    "th08 Spell Practice Last Spell": "Last",
    "th08 Spell Condition Line 1 205": "挑戦可能条件：望月（エキストラ）をスペルカード７枚以上取得して",
    "th08 Spell Condition Line 2 205": "　　　　　　　クリアする。",
    "th08 Spell Condition Line 1 206": "挑戦可能条件：通常モードFinalBを２キャラ以上クリアする。",
    "th08 Spell Condition Line 2 206 207 209": "　　　　　　　難易度不問。",
    "th08 Spell Condition Line 1 207": "挑戦可能条件：通常モードFinalBを３キャラ以上クリアする。",
    "th08 Spell Condition Line 1 208": "挑戦可能条件：スペルカードモードでスペルカードを50枚以上取得する。",
    "th08 Spell Condition Line 2 208 211 217 220": "　　　　　　　全キャラ合計。",
    "th08 Spell Condition Line 1 209": "挑戦可能条件：通常モードFinalBを４キャラ以上クリアする。",
    "th08 Spell Condition Line 1 210": "挑戦可能条件：No.%.3dを取得する。",
    "th08 Spell Condition Line 1 211": "挑戦可能条件：スペルカードモードでラストスペルを15枚以上取得する。",
    "th08 Spell Condition Line 1 212": "挑戦可能条件：No.%.3d,%.3dを取得し",
    "th08 Spell Condition Line 2 212": "　　　　　　　かつ、No.%.3dを一度でも見る。",
    "th08 Spell Condition Line 1 213": "挑戦可能条件：No.%.3d,%.3d,%.3dを一度でも見る。",
    "th08 Spell Condition Line 2 213 214 222": "　　　　　　　取得の必要はない。",
    "th08 Spell Condition Line 1 214": "挑戦可能条件：No.%.3d,%.3d,%.3d,%.3dを一度でも見る。",
    "th08 Spell Condition Line 1 215": "挑戦可能条件：魔理沙（単独使用）で三日月（ノーマル）の",
    "th08 Spell Condition Line 2 215": "　　　　　　　スペルカードを全て取得。",
    "th08 Spell Condition Line 1 216": "挑戦可能条件：霊夢（単独使用）で上つ弓張（ハード）以上をクリア。",
    "th08 Spell Condition Line 2 216": "　　　　　　　最終面はFinalBのみ。",
    "th08 Spell Condition Line 1 217": "挑戦可能条件：スペルカードモードでスペルカードを120枚以上取得する",
    "th08 Spell Condition Line 1 218": "挑戦可能条件：通常モードFinalBを６キャラ以上クリアする。",
    "th08 Spell Condition Line 2 218": "　　　　　　　",
    "th08 Spell Condition Line 1 219": "挑戦可能条件：望月（エキストラ）を３キャラ以上クリアする。",
    "th08 Spell Condition Line 1 220": "挑戦可能条件：スペルカードモードでラストスペルを30枚以上取得する。",
    "th08 Spell Condition Line 1 221": "挑戦可能条件：待宵（ルナティック）をクリアする。",
    "th08 Spell Condition Line 2 221": "　　　　　　　コンティニュー可、使用キャラ不問。",
    "th08 Spell Condition Line 1 222": "挑戦可能条件：これ以外のラストワードを全て一度見る。",
    "th07 MAX": "MAX",
    "th07 Stats Header Easy": "Easy",
    "th07 Stats Header Normal": "Norm",
    "th07 Stats Header Hard": "Hard",
    "th07 Stats Header Lunatic": "Luna",
    "th07 Stats Header Extra": "Extra",
    "th07 Stats Header Phantasm": "Phants",
    "th07 Stats Header Total": "Total",
    "Stats Time Since Startup": "Time Since Start-up",
    "Stats Total Playtime": "Total Playtime",
    "Stats Play Count": "Play Count",
    "Stats Clear Count": "Clear Count",
    "Stats Continue": "Continues",
    "Stats Practice": "Practice",
    "Stats Retries": "Retries",
    "Serif font": "MS Mincho",
    "th16_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:-- Season  Stage -  ---%%",
    "th16_ascii_score_spring": "Spring",
    "th16_ascii_score_summer": "Summer",
    "th16_ascii_score_autumn": "Autumn",
    "th16_ascii_score_winter": "Winter",
    "th16_ascii_score_sp": "Sp",
    "th16_ascii_score_sm": "Sm",
    "th16_ascii_score_at": "At",
    "th16_ascii_score_wt": "Wt",
    "th105_init_failed": "初期化失敗",
    "th105_replay_return_to_select": "セレクトへ戻ります。リプレイを保存しますか？",
    "th105_replay_return_to_title": "タイトルに戻ります。リプレイを保存しますか？",
    "th105_replay_saved": "リプレイを保存しました",
    "th105_replay_save": "リプレイを保存しますか？",
    "th105_replay_delete": "削除しますか？",
    "th105_continue": "コンティニューしますか？   あと%d回",
    "th105_netplay_select_addr": "接続先を選択してください",
    "th105_netplay_port": "使用するポート番号を入力してください",
    "th105_netplay_enter_addr": "接続先のアドレスを入力してください",
    "th105_netplay_allow_spectating": "観戦を有効にしますか？",
    "th105_netplay_await": "接続受付中",
    "th105_netplay_no_spectating": "観戦を受け付けていません",
    "th105_netplay_game_not_available": "対戦が行われていません",
    "th105_netplay_connection_failed": "接続に失敗しました",
    "th105_netplay_connecting": "接続中",
    "th105_netplay_connect_for_match": "対戦をしますか？",
    "th105_netplay_confirm_address": " へ接続します",
    "th105_netplay_already_playing": "すでに対戦中です",
    "th105_netplay_already_playing_spectate": "すでに対戦中です 観戦しますか？",
    "th105_delete_failed": "削除に失敗しました",
    "th105_delete_suceeded": "削除しました",
    "th105_profile_save_changes": "構築を終了します。編集内容をセーブしますか？",
    "th105_profile_deck_too_big": "デッキが20枚ではありません",
    "th105_profile_creation_failed": " の作成に失敗しﾜした",
    "th105_profile_created": " を作成しました",
    "th105_profile_copied": "コピーしました",
    "th105_profile_copy_failed": "コピーに失敗しました",
    "th105_profil_rename_failed": "名前の変更に失敗しました",
    "th105_profil_renamed": "名前を変更しました",
    "th105_profile_overwrite": " に上書きしますｩ？",
    "th105_profile_will_copy": " をコピーしますｩ？",
    "th105_profile_will_delete": " を削除しますか？",
    "th123_replay_create_folder_failed": "replayフォルダの生成に失敗",
    "th123_profile_create_folder_failed": "profileフォルダの生成に失敗",
    "th165_ascii_replay_empty": "No.%.2d ------------ --/--/-- ---------",
    "th165_ascii_replay_sun": "    Sun",
    "th165_ascii_replay_mon": "    Mon",
    "th165_ascii_replay_tue": "    Tue",
    "th165_ascii_replay_wed": "    Wed",
    "th165_ascii_replay_thu": "    Thu",
    "th165_ascii_replay_fri": "    Fri",
    "th165_ascii_replay_sat": "    Sat",
    "th165_ascii_replay_sun2": "2nd Sun",
    "th165_ascii_replay_mon2": "2nd Mon",
    "th165_ascii_replay_tue2": "2nd Tue",
    "th165_ascii_replay_wed2": "2nd Wed",
    "th165_ascii_replay_thu2": "2nd Thu",
    "th165_ascii_replay_fri2": "2nd Fri",
    "th165_ascii_replay_sat2": "2nd Sat",
    "th165_ascii_replay_sun3": "3rd Sun",
    "th165_ascii_replay_mon3": "3rd Mon",
    "th165_ascii_replay_tue3": "3rd Tue",
    "th165_ascii_replay_wed3": "3rd Wed",
    "th165_ascii_replay_thu3": "3rd Thu",
    "th165_ascii_replay_fri3": "3rd Fri",
    "th165_ascii_replay_sat3": "3rd Sat",
    "th165_ascii_replay_diary": "  Diary",
    "th165 JP": "秘封ナイトメアダイアリー",
    "th16 config": "東方天空璋　環境カスタムプログラム",
    "th165 config": "秘封ナイトメアダイアリー　環境カスタムプログラム",
    "th16": "東方天空璋　～ Hidden Star in Four Seasons",
    "th06 BGM In-game format": "♪%s",
    "th06 Stats ReimuA": "博麗 霊夢 (霊)",
    "th06 Stats ReimuB": "博麗 霊夢 (夢)",
    "th06 Stats MarisaA": "霧雨 魔理沙 (魔)",
    "th06 Stats MarisaB": "霧雨 魔理沙 (恋)",
    "th06_ascii_centered_stage": "STAGE %d",
    "th06_ascii_centered_stage_final": "FINAL STAGE",
    "th06_ascii_centered_stage_extra": "EXTRA STAGE",
    "th06_ascii_centered_stage_demo": "DEMO PLAY",
    "th06_ascii_centered_spell_bonus": "Spell Card Bonus!",
    "th06_ascii_fullpower": "Full Power Mode!!",
    "th06_ascii_bonus_format": "BONUS %8d",
    "th06_ascii_clear_header": "Stage Clear",
    "th06_ascii_clear_header_all": "All Clear!",
    "th06_ascii_clear_bonus_stage": "Stage * 1000 = %5d",
    "th06_ascii_clear_bonus_power": "Power *  100 = %5d",
    "th06_ascii_clear_bonus_graze": "Graze *   10 = %5d",
    "th06_ascii_clear_bonus_point": "    * Point Item %3d",
    "th06_ascii_clear_bonus_player": "Player    = %8d",
    "th06_ascii_clear_bonus_bomb": "Bomb      = %8d",
    "th06_ascii_clear_bonus_easy": "Easy Rank      * 0.5",
    "th06_ascii_clear_bonus_normal": "Normal Rank    * 1.0",
    "th06_ascii_clear_bonus_hard": "Hard Rank      * 1.2",
    "th06_ascii_clear_bonus_lunatic": "Lunatic Rank   * 1.5",
    "th06_ascii_clear_bonus_extra": "Extra Rank     * 2.0",
    "th06_ascii_clear_bonus_penalty_0.5": "Player Penalty * 0.5",
    "th06_ascii_clear_bonus_penalty_0.2": "Player Penalty * 0.2",
    "th06_ascii_clear_bonus_total": "Total     = %8d",
    "th06_ascii_replay_header": "No.   Name      Date     Player   Rank",
    "th06_ascii_replay": "%s %8s  %8s %-7s  %-7s",
    "th06_ascii_replay_save_header": "No.   Name     Date     Player  Score",
    "th06_ascii_replay_save_empty": "No.%.2d -------- --/--/-- -------          0",
    "th06_ascii_replay_save": "No.%.2d %8s %8s %7s %10d",
    "th06_ascii_2_digit_number_format": "No.%2d",
    "th06_ascii_replay_user": "User",
    "th06_ascii_reimu_a": "ReimuA",
    "th06_ascii_reimu_b": "ReimuB",
    "th06_ascii_marisa_a": "MarisaA",
    "th06_ascii_marisa_b": "MarisaB",
    "th06_ascii_easy": "Easy",
    "th06_ascii_normal": "Normal",
    "th06_ascii_hard": "Hard",
    "th06_ascii_lunatic": "Lunatic",
    "th06_ascii_extra": "Extra",
    "th06_ascii_replay_stage_header": "Stage   LastScore",
    "th06_ascii_replay_stage_empty": "%-6s  ---------",
    "th06_ascii_replay_stage": "%-6s %10d",
    "th06_ascii_replay_stage_1": "Stage1",
    "th06_ascii_replay_stage_2": "Stage2",
    "th06_ascii_replay_stage_3": "Stage3",
    "th06_ascii_replay_stage_4": "Stage4",
    "th06_ascii_replay_stage_5": "Stage5",
    "th06_ascii_replay_stage_6": "Stage6",
    "th06_ascii_replay_stage_extra": "Extra",
    "th06_ascii_result_clear": "(C)",
    "th16 Dialog Fullscreen": "フルスクリーン",
    "th17 config": "東方鬼形獣　環境カスタムプログラム",
    "th16 half rate": "１／２回",
    "th16 third rate": "１／３回",
    "th16 refresh rate": "描画間隔",
    "th16 full rate": "毎回（推奨）",
    "th16 no save": "保存せずに終了",
    "th16 slowshot": "ショットボタン押しっぱなしで低速移動する",
    "th16 input latency": "入力のレイテンシ",
    "th16 stable input": "安定（通常では上手く動かない場合）",
    "th16 normal input": "通常（CPUの占拠率が低い）",
    "th16 automatic input": "自動（最速の反応を自動的に検出）＊推奨",
    "th16 fast input": "高速（自動では正常に動作しない場合）",
    "th16 input description": "　入力のレイテンシでは入力のレスポンスを微調整する事が出来ます。\n　「安定」「通常」は前作までのレスポンスです。\n　「自動」はマシンの性能が十分なのであれば最速のレスポンスを期待できます。\n　「高速」は「自動」と同程度のレスポンスですが、一部画面が乱れる事があります。\n　＊描画間隔が「毎回」以外では無効です＊",
    "th16 Dialog Always ask": "起動時に毎回訊ねる",
    "th16 sensitivity description": "上下左右の入力が鈍い場合は減らし、敏感過ぎる場合は増やしてください\n（default:600）",
    "th16 joypad sensitivity": "パッドの遊び",
    "th16 default": "初期設定に戻す",
    "th16 JP": "東方天空璋",
    "th17 JP": "東方鬼形獣",
    "th01": "東方靈異伝　～ The Highly Responsive to Prayers",
    "th02": "東方封魔録　～ the Story of Eastern Wonderland",
    "th03": "東方夢時空　～ Phantasmagoria of Dim.Dream",
    "th04": "東方幻想郷　～ Lotus Land Story",
    "th05": "東方怪綺談　～ Mystic Square",
    "th06": "東方紅魔郷　～ the Embodiment of Scarlet Devil",
    "th07": "東方妖々夢　～ Perfect Cherry Blossom",
    "th08": "東方永夜抄　～ Imperishable Night",
    "th09": "東方花映塚　～ Phantasmagoria of Flower View",
    "th095": "東方文花帖　～ Shoot the Bullet",
    "th10": "東方風神録　～ Mountain of Faith",
    "th11": "東方地霊殿　～ Subterranean Animism",
    "th12": "東方星蓮船　～ Undefined Fantastic Object",
    "th125": "ダブルスポイラー　～ 東方文花帖",
    "th128": "妖精大戦争　～ 東方三月精",
    "th13": "東方神霊廟　～ Ten Desires",
    "th14": "東方輝針城　～ Double Dealing Character",
    "th143": "弾幕アマノジャク　～ Impossible Spell Card",
    "th15": "東方紺珠伝　～ Legacy of Lunatic Kingdom",
    "th165": "秘封ナイトメアダイアリー　〜 Violet Detector",
    "th17": "東方鬼形獣　～ Wily Beast and Weakest Creature",
    "th075": "東方萃夢想　～ Immaterial and Missing Power",
    "th105": "東方緋想天 ～ Scarlet Weather Rhapsody",
    "th123": "東方非想天則　～ 超弩級ギニョルの謎を追え",
    "th135": "東方心綺楼　～ Hopeless Masquerade",
    "th145": "東方深秘録　～ Urban Legend in Limbo",
    "th155": "東方憑依華　～ Antinomy of Common Flowers",
    "alcostg": "黄昏酒場～Uwabami Breakers～",
    "nsml": "魔理沙と6つのキノコ - New Super Marisa Land",
    "megamari": "MegaMari - 魔理沙の野望",
    "marilega": "MarisaLand Legacy",
    "th17 Trophy Get": "の実績を手に入れた",
    "th175": "東方剛欲異聞　～ 水没した沈愁地獄",
    "th07 Stage Clear": "Stage Clear",
    "th07 All Clear": "All Clear",
    "th07 Clear Bonus Format": "Clear  = %8d",
    "th07 Clear Point Items Format": "Point  = %8d",
    "th07 Clear Graze Format": "Graze  = %8d",
    "th07 Clear Cherry Format": "Cherry = %8d0",
    "th07 Clear Bonus Life Format": "Player =%9d",
    "th07 Clear Bonus Bomb Format": "Bomb   = %8d",
    "th07 Clear Easy Multiplier": "Easy Rank    *0.5",
    "th07 Clear Normal Multiplier": "Normal Rank  *1.0",
    "th07 Clear Hard Multiplier": "Hard Rank    *1.2",
    "th07 Clear Lunatic Multiplier": "Lunatic Rank *1.5",
    "th07 Clear Extra Multiplier": "Extra Rank   *2.0",
    "th07 Clear Phantasm Multiplier": "Phantasm Rank*2.0",
    "th07 Clear Player Penalty*0.5": "Player Penalty*0.5",
    "th07 Clear Player Penalty*0.2": "Player Penalty*0.2",
    "th07 Clear Player Penalty*0.1": "Player Penalty*0.1",
    "th07 Clear Player Penalty*0.05": "Player Penalty*0.05",
    "th07 Clear Total Score Format": "Total = %8d0",
    "th08 Clear Time Orbs Format": "Time  = %8d0",
    "th08 Clear Human Format": "over-80%% = %3d.%.2d%%",
    "th08 Clear Youkai Format": "over 80%% = %3d.%.2d%%",
    "th08 Clear Last Time Format": "Last Time = %2d:%.2d",
    "th08 Clear Night Bonus": "Night Bonus",
    "th07 Supernatural Border": "Supernatural Border!!",
    "th07 CherryPoint Max": "CherryPoint Max!",
    "th07 Border Bonus Format": "Border Bonus %7d"
}